kind: ConfigMap
apiVersion: v1
metadata:
  name: service-a-envoy-configmap
  namespace: monitoring
data:
  envoy-config: |
    access_log_path: "/tmp/admin_access.log"
      address:
        socket_address:
          - address: "127.0.0.1"
            port_value: 9901
    static_resources:
      listeners:
        -
          name: "service-monitoring-java-web-app-a-svc-http-listener"
          address:
            socket_address:
              address: "0.0.0.0"
              port_value: 8080
          filter_chains:
            -
              filters:
                -
                  name: "envoy.http_connection_manager"
                  config:
                    stat_prefix: "ingress"
                    codec_type: "AUTO"
                    route_config:
                      name: "service-monitoring-java-web-app-a-svc-http-route"
                      virtual_hosts:
                        -
                          name: "service-monitoring-java-web-app-a-svc-http-route"
                          domains:
                            - "*"
                          routes:
                            -
                              match:
                                prefix: "/"
                              route:
                                cluster: "service_monitoring-java-web-app-a"
                    http_filters:
                      -
                        name: "envoy.router"

      clusters:
        -
          name: "service_monitoring-java-web-app-a"
          connect_timeout: "0.25s"
          type: "strict_dns"
          lb_policy: "ROUND_ROBIN"
          hosts:
            -
              socket_address:
                address: "service_monitoring-java-web-app-a"
                port_value: 8080

