apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monitoring-java-web-app-a
  name: monitoring-java-web-app-a
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring-java-web-app-a
  template:
    metadata:
      labels:
        app: monitoring-java-web-app-a

    spec:
      containers:
        - image: gabrieldyck/monitoring-java-web-app:latest
          name: monitoring-java-web-app-a
          env:
            - name: ip
              value: "172.20.178.251"
          ports:
            - containerPort: 8081
              name: envoy-metrics
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: http-metrics
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
        - name: nebula-proxy
          image: envoyproxy/envoy:latest
          ports:
            - containerPort: 8081
              protocol: TCP
              name: envoy-admin
            - containerPort: 8786
              protocol: TCP
              name: envoy-web
          volumeMounts:
            - name: envoy-config-volume
              mountPath: /etc/envoy-config/
          command: ["/usr/local/bin/envoy"]
          args: ["-c", "/etc/envoy-config/config.yaml", "-l", "debug","--service-cluster","service-monitoring-java-web-app-a","--service-node","service-monitoring-java-web-app-a", "--log-format", "[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v"]
      volumes:
        - name: envoy-config-volume
          configMap:
            name: service-a-envoy-configmap
            items:
              - key: envoy-config
                path: config.yaml