apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: monitoring-java-web-app-a
  name: monitoring-java-web-app-a
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      service: monitoring-java-web-app-a
  template:
    metadata:
      labels:
        service: monitoring-java-web-app-a
        envoy: envoy
    spec:
      containers:
        - image: gabrieldyck/monitoring-java-web-app:latest
          imagePullPolicy: Always
          name: monitoring-java-web-app-a
          env:
            - name: ip
              value: "localhost"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9800
              name: http-metrics
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 1000m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
        - name: envoy
          image: envoyproxy/envoy:latest
          ports:
            - containerPort: 8081
              protocol: TCP
              name: envoy-metrics
            - containerPort: 8786
              protocol: TCP
            - containerPort: 8788
              name: ext-service
          volumeMounts:
            - name: envoy-config-volume
              mountPath: /etc/envoy-config/
            - name: accesslog-shared-data
              mountPath: /tmp/
          command: ["/usr/local/bin/envoy"]
          args: ["-c", "/etc/envoy-config/config.yaml", "-l", "debug","--service-cluster","service-monitoring-java-web-app-a","--service-node","service-monitoring-java-web-app-a", "--log-format", "[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v"]
        - name: envy
          image: 168448339441.dkr.ecr.us-east-1.amazonaws.com/envy:0.0.25
          env:
            - name: ENVIRONMENT
              value: "beta"
          ports:
            - containerPort: 9292
              name: http-envy
          volumeMounts:
            - name: envy-config
              mountPath: /etc/app/config/
            - name: accesslog-shared-data
              mountPath: /tmp/
          resources:
            limits:
              cpu: 1
              memory: 1000Mi
            requests:
              cpu: 1
              memory: 1000Mi
      volumes:
        - name: envoy-config-volume
          configMap:
            name: service-a-envoy-configmap
            items:
              - key: envoy-config
                path: config.yaml
        - name: envy-config
          configMap:
            name: envy-config
        - name: accesslog-shared-data
          emptyDir: {}