apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: service-a-envy
  namespace: monitoring
spec:
  podMetricsEndpoints:
    - interval: 15s
      port: http-envy
  selector:
    matchLabels:
      service: monitoring-java-web-app-a