apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitoring-java-web-app-a

  name: jmx-a
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: http-metrics
    port: 9090
    targetPort: http-metrics
  - name: envoy-metrics
    port: 8081
    targetPort: envoy-metrics
  selector:
    app: monitoring-java-web-app-a
