apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jmx-a
  namespace: monitoring
spec:
  endpoints:
    - interval: 15s
      port: http-metrics
  selector:
    matchLabels:
      service: monitoring-java-web-app-a