apiVersion: apps/v1
kind: Deployment
metadata:
  name: statsd-exporter
  namespace: monitoring
  labels:
    app: statsd-exporter

spec:
  replicas: 2
  selector:
    matchLabels:
      app: statsd-exporter
  template:
    metadata:
      labels:
        app: statsd-exporter
    spec:
      containers:
        - name: statsd-exporter
          image: prom/statsd-exporter:latest
          ports:
            - name: http-metrics
              containerPort: 9102
            - name: push-metrics
              containerPort: 9125
