apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jmx-b
  namespace: monitoring
spec:
  endpoints:
    - interval: 15s
      port: http-metrics
  selector:
    matchLabels:
      application: monitoring-java-web-app-b
