apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitoring-java-web-app-b
  name: jmx-b
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: http-metrics
    port: 9090
    targetPort: http-metrics
  selector:
    app: monitoring-java-web-app-b
