{
 "title": "Services / Traffic / Clients",
 "tags": [
  "services",
  "traffic",
  "clients"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "dest",
    "query": "label_values(source_cluster_destination_upstream_rq_2xx,destination)"
   },
   {
    "name": "orig",
    "query": "label_values(source_cluster_destination_upstream_rq_2xx,source)"
   }
  ]
 },
 "panels": [
  { "title": "Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client Request Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(source_cluster_destination_upstream_rq_completed{source=~\"$orig\", destination=~\"$dest\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(source_cluster_destination_upstream_rq_completed{source=~\"$orig\", destination=~\"$dest\"}[1m])) by (source)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Top 10 Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(rate(source_cluster_destination_upstream_rq_completed{source=~\"$orig\", destination=~\"$dest\"}[1m])) by (source))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Top Clients Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (source) (rate(source_cluster_destination_upstream_rq_completed{source=~\"$orig\", destination=~\"$dest\"}[1m])) /      sum by (source) (rate(source_cluster_destination_upstream_rq_completed{destination=~\"$dest\"}[1m])) * 100",
     "legendFormat": "{{source}}"
    }
   ]
  },
  { "title": "Status Codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Request Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(source_cluster_destination_upstream_rq_completed{source=~\"$orig\", destination=~\"$dest\"}[1m]))",
     "legendFormat": "{{source}}:{{instance}}-->{{destination}}"
    }
   ]
  },
  {
   "title": "HttpStatus 200 Request Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(source_cluster_destination_upstream_rq_2xx{source=~\"$orig\", destination=~\"$dest\"}[1m]))",
     "legendFormat": "{{source}}:{{instance}}-->{{destination}}"
    }
   ]
  },
  {
   "title": "HttpStatus 400 Request Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(source_cluster_destination_upstream_rq_4xx{source=~\"$orig\", destination=~\"$dest\"}[1m]))",
     "legendFormat": "{{source}}:{{instance}}-->{{destination}}"
    }
   ]
  },
  {
   "title": "HttpStatus 500 Request Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(source_cluster_destination_upstream_rq_5xx{source=~\"$orig\", destination=~\"$dest\"}[1m]))",
     "legendFormat": "{{source}}:{{instance}}-->{{destination}}"
    }
   ]
  },
  {
   "title": "HttpStatus 200 Request %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(source_cluster_destination_upstream_rq_2xx{source=~\"$orig\", destination=~\"$dest\"}[1m]))  / sum(rate(source_cluster_destination_upstream_rq_completed{source=~\"$orig\", destination=~\"$dest\"}[1m])) * 100",
     "legendFormat": "{{source}}:{{instance}}-->{{destination}}"
    }
   ]
  },
  {
   "title": "HttpStatus 400 Request %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(source_cluster_destination_upstream_rq_4xx{source=~\"$orig\", destination=~\"$dest\"}[1m]))   / sum(rate(source_cluster_destination_upstream_rq_completed{source=~\"$orig\", destination=~\"$dest\"}[1m])) * 100",
     "legendFormat": "{{source}}:{{instance}}-->{{destination}}"
    }
   ]
  },
  {
   "title": "HttpStatus 500 Request %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(source_cluster_destination_upstream_rq_5xx{source=~\"$orig\", destination=~\"$dest\"}[1m])) / sum(rate(source_cluster_destination_upstream_rq_completed{source=~\"$orig\", destination=~\"$dest\"}[1m])) *100",
     "legendFormat": "{{source}}:{{instance}}-->{{destination}}"
    }
   ]
  },
  {
   "title": "Request Status 2XX",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "repeat": "destination",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(source_cluster_destination_upstream_rq_2xx{source=~\"$orig\", destination=~\"$dest\"}[1m])) by (source)",
     "legendFormat": "{{source}}->{{destination}}"
    }
   ]
  },
  {
   "title": "Request Status: 4XX ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(source_cluster_destination_upstream_rq_4xx{source=~\"$orig\", destination=~\"$dest\"}[1m])) by (source)",
     "legendFormat": "{{source}}-->{{destination}}"
    }
   ]
  },
  {
   "title": "Request Status: 5XX ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(source_cluster_destination_upstream_rq_5xx{source=~\"$orig\", destination=~\"$dest\"}[1m])) by (source)",
     "legendFormat": "{{source}}->{{destination}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "[[source]]_cluster_[[destination]]_upstream_rq_time",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}