apiVersion: v1
kind: ConfigMap
metadata:
  name: service-b-envoy-configmap
  namespace: monitoring
data:
  envoy-config: |
    stats_sinks:
      - name: "envoy.statsd"
        config:
          tcp_cluster_name: "statsd-exporter"
          prefix: service-b
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 80
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: auto
              stat_prefix: ingress_http_b
              route_config:
                name: local_route
                virtual_hosts:
                - name: service
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: local_service_b
              http_filters:
              - name: envoy.router
                config: {}
      clusters:
      - name: "statsd-exporter"
        connect_timeout: "0.25s"
        type: "strict_dns"
        lb_policy: "ROUND_ROBIN"
        hosts:
        - socket_address:
            address: "statsd-exporter"
            port_value: 9125
      - name: local_service_b
        connect_timeout: 0.25s
        type: strict_dns
        lb_policy: round_robin
        hosts:
        - socket_address:
            address: 127.0.0.1
            port_value: 8080
      - name: service_a
        connect_timeout: 0.25s
        type: strict_dns
        lb_policy: round_robin
        hosts:
        - socket_address:
            address: jmx-a
            port_value: 80
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8081