apiVersion: v1
kind: ConfigMap
metadata:
  name: service-b-envoy-configmap
  namespace: monitoring
data:
  envoy-config: |
    static_resources:
      listeners:
      - name: "service-monitoring-java-web-app-b-svc-http-listener"
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 18080
        use_original_dst: true
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: auto
              stat_prefix: ingress_http
              route_config:
                name: service-monitoring-java-web-app-b-svc-http-route
                virtual_hosts:
                - name: service-monitoring-java-web-app-b-svc-http-route
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: service_monitoring-java-web-app-b
              http_filters:
              - name: envoy.router
                config: {}
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 18080
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              stat_prefix: egress_http
              route_config:
                name: service_monitoring-java-web-app-a_route
                virtual_hosts:
                - name: service_monitoring-java-web-app-a
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: service_monitoring-java-web-app-a
              http_filters:
              - name: envoy.router
                config: {}
      clusters:
      - name: service_monitoring-java-web-app-b
        connect_timeout: 0.250s
        type: strict_dns
        lb_policy: round_robin
        hosts:
        - socket_address:
            address: monitoring-java-web-app-b
            port_value: 18080
      - name: service_monitoring-java-web-app-a
        connect_timeout: 0.250s
        type: strict_dns
        lb_policy: round_robin
        hosts:
        - socket_address:
            address: monitoring-java-web-app-a
            port_value: 18080
    admin:
      access_log_path: "/var/log/admin-access.log"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001