apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: statsd-exporter
  namespace: monitoring
spec:
  endpoints:
    - interval: 15s
      port: http-metrics
  selector:
    matchLabels:
      service: statsd-exporter