apiVersion: v1
kind: Service
metadata:
  labels:
    service: statsd-exporter
  name: statsd-exporter
  namespace: monitoring
spec:
  ports:
    - name: http-metrics
      port: 9102
      targetPort: http-metrics
    - name: push-metrics
      port: 9125
      targetPort: push-metrics
  selector:
    service: statsd-exporter