apiVersion: v1
kind: Service
metadata:
  labels:
    service: envoy
  name: envoy
  namespace: monitoring
spec:
  ports:
    - name: envoy-metrics
      port: 8001
      targetPort: envoy-metrics
  selector:
    envoy: envoy