apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy
  namespace: monitoring
spec:
  endpoints:
    - interval: 15s
      port: envoy-metrics
      path: /stats/prometheus
  selector:
    matchLabels:
      service: envoy