apiVersion: v1
kind: Service
metadata:
  labels:
    app: envoy
  name: envoy
  namespace: monitoring
spec:
  ports:
    - name: envoy-metrics
      port: 8081
      targetPort: envoy-metrics
  selector:
    envoy: envoy